### ISSUE TITLE
Misleading synchronizing icon

### ISSUE THREAD

**Issue by Hascki** [qtoggle/qtoggleserver#52]
The check icon in the top right side of the screen should be hidden unless there are uncommited changes.

**Comment by ccrisan** [comment]
Proposed solution includes:
 * showing the sync icon for at least 1 second
 * hiding the _check_ icon while not syncing

**Comment by ccrisan** [comment]
Fixed via https://github.com/qtoggle/qui/commit/e1319a5ce1cbc6ac61c56ae1ca6eab1f2c578854.
