### ISSUE TITLE
Cannot create panel assigned to group

### ISSUE THREAD

**Issue by fulf** [qtoggle/qtoggleserver#55]
**Describe the bug**
I cannot create `Panel`s in `Group`s as the application raises an error whenever I try to add a `Widget`

**Steps to reproduce**
1. On the `Dashboard`, create a `Group` named `Living Room`
2. In the `Living Room` group create a panel named `Lights`
3. Add any `Widget` to the `Lights` panel
4. The below error occurs
```
An unexpected error occurred.
Application reloading is recommended.
```

**Expected behavior**
I am able to create a `Panel` in the selected `Group` with any `Widgets` I choose.

**Installation Details**
 - qToggleServer version: 0.19.1.0
 - Installed using: qToggleOS
 - Server running on: Raspberry Pi 3
 - App running on (if applicable): macOS Catalina, Chrome 81.0.4044.129

**Log files**
[console.errors](https://gist.github.com/fulf/541fff5e0dee08ba057b0c9951447e4b)

**Comment by ccrisan** [comment]
Fixed via fc495ba13aaac0e0731f61ecccd0c74b4ca89eb0.
