### ISSUE TITLE
Invalid hostname character allowed in 'Device Name'

### ISSUE THREAD

**Issue by 13commander** [qtoggle/qtoggleserver#62]
**Describe the bug:**
After changing the 'Device Name' to eq. 'My_Device' and a reboot, adding the new device / URL becomes impossible because of the '_' character.

**Steps to reproduce:**
- Go to Devices and select a device
- Change the 'Device Name' to 'My_Device'
- Save and reboot device
- Delete changed device from the device list
- add the new: http://My_Device
=>
- "Enter a valid URL." error is shown

**Expected behavior:**
Consistency between the 'Device Name' allowed characters and the URL 'allowed characters'. Preferably the 'Device Name' should respect the hostname allowed character set

**Installation details:**
 - qToggleServer version: 0.20.2-beta.4
 - Installed using: qToggleOS
 - Server running on: e.g. Raspberry Pi 4

**Comment by ccrisan** [comment]
Fixed via https://github.com/qtoggle/qui/commit/f2b1af40acaf362617fe110cf4e98362ab1bc9d6. Will be available in 0.20.2.
