### ISSUE TITLE
Device URL change is needed when 'Device Name' is modified

### ISSUE THREAD

**Issue by 13commander** [qtoggle/qtoggleserver#63]
**Is your improvement proposal related to a problem? Please describe:**
Changing the name of added Devices is pretty cumbersome. Currently when I want to change the 'Device Name', which is functionally the hostname, the URL of the device does not change. Removing the device and adding it again is required in order to access the new URL.  

**Possible solutions:**
1. Make the URL field editable for the Devices
2. Automatic URL change when 'Device Name' is changed. This requires additional actions:
- Either a device reboot after the name and URL change
- Or a 'request' to the DHCP server to change the device hostname 

**Provide any mockups, sketches or screenshots that clarify your idea:**
![image](https://user-images.githubusercontent.com/12201591/82758501-99b8ef80-9def-11ea-8306-1547b60e0b4e.png)

**Additional context:**
This is more of a problem when a Dashboard Configuration has already been made and the device needs to be re-added.

**Comment by ccrisan** [comment]
Fixed via https://github.com/qtoggle/qtoggleserver/pull/87.

Upon renaming, the approach is basically as follows:
 * the device is removed and re-added (new name will be picked up)
 * if device name is used as host, the device will be re-added using new hostname:
    * a temporary local DNS mapping will ensure hostname lookup until DHCP is informed of change
    * the device is explicitly reset using `POST /reset` so that it reconnects and thus updates hostname on local router via DHCP
